services:
  - type: web
    name: Code_Vault_Backend
    env: node
    plan: free
    repo: https://github.com/ASP-31/Codevault
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your_mongo_url
      - key: JWT_SECRET
        value: your_secret
      - key: PORT
        value: 3000
